/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Project Admin API
 * OpenAPI spec version: 1.0
 */
import { useInfiniteQuery, useMutation, useQuery } from '@tanstack/react-query';
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseInfiniteQueryResult,
    DefinedUseQueryResult,
    InfiniteData,
    MutationFunction,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseInfiniteQueryOptions,
    UseInfiniteQueryResult,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from '@tanstack/react-query';
import type { BlogList, CreateBlogDto } from '../api.schemas';
import { axiosCall } from '.././api.axios';
import type { ErrorType } from '.././api.axios';

export const blogCreatePost = (createBlogDto: CreateBlogDto, signal?: AbortSignal) => {
    return axiosCall<void>({
        url: `/blog`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: createBlogDto,
        signal,
    });
};

export const getBlogCreatePostMutationOptions = <TError = ErrorType<unknown>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof blogCreatePost>>,
        TError,
        { data: CreateBlogDto },
        TContext
    >;
}): UseMutationOptions<Awaited<ReturnType<typeof blogCreatePost>>, TError, { data: CreateBlogDto }, TContext> => {
    const { mutation: mutationOptions } = options ?? {};

    const mutationFn: MutationFunction<Awaited<ReturnType<typeof blogCreatePost>>, { data: CreateBlogDto }> = props => {
        const { data } = props ?? {};

        return blogCreatePost(data);
    };

    return { mutationFn, ...mutationOptions };
};

export type BlogCreatePostMutationResult = NonNullable<Awaited<ReturnType<typeof blogCreatePost>>>;
export type BlogCreatePostMutationBody = CreateBlogDto;
export type BlogCreatePostMutationError = ErrorType<unknown>;

export const useBlogCreatePost = <TError = ErrorType<unknown>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof blogCreatePost>>,
        TError,
        { data: CreateBlogDto },
        TContext
    >;
}): UseMutationResult<Awaited<ReturnType<typeof blogCreatePost>>, TError, { data: CreateBlogDto }, TContext> => {
    const mutationOptions = getBlogCreatePostMutationOptions(options);

    return useMutation(mutationOptions);
};
export const blogGetBlogList = (signal?: AbortSignal) => {
    return axiosCall<BlogList>({ url: `/blog/list`, method: 'GET', signal });
};

export const getBlogGetBlogListQueryKey = () => {
    return [`/blog/list`] as const;
};

export const getBlogGetBlogListInfiniteQueryOptions = <
    TData = InfiniteData<Awaited<ReturnType<typeof blogGetBlogList>>>,
    TError = ErrorType<unknown>,
>(options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof blogGetBlogList>>, TError, TData>>;
}) => {
    const { query: queryOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getBlogGetBlogListQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof blogGetBlogList>>> = ({ signal }) => blogGetBlogList(signal);

    return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof blogGetBlogList>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData> };
};

export type BlogGetBlogListInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof blogGetBlogList>>>;
export type BlogGetBlogListInfiniteQueryError = ErrorType<unknown>;

export function useBlogGetBlogListInfinite<
    TData = InfiniteData<Awaited<ReturnType<typeof blogGetBlogList>>>,
    TError = ErrorType<unknown>,
>(options: {
    query: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof blogGetBlogList>>, TError, TData>> &
        Pick<DefinedInitialDataOptions<Awaited<ReturnType<typeof blogGetBlogList>>, TError, TData>, 'initialData'>;
}): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useBlogGetBlogListInfinite<
    TData = InfiniteData<Awaited<ReturnType<typeof blogGetBlogList>>>,
    TError = ErrorType<unknown>,
>(options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof blogGetBlogList>>, TError, TData>> &
        Pick<UndefinedInitialDataOptions<Awaited<ReturnType<typeof blogGetBlogList>>, TError, TData>, 'initialData'>;
}): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useBlogGetBlogListInfinite<
    TData = InfiniteData<Awaited<ReturnType<typeof blogGetBlogList>>>,
    TError = ErrorType<unknown>,
>(options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof blogGetBlogList>>, TError, TData>>;
}): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

export function useBlogGetBlogListInfinite<
    TData = InfiniteData<Awaited<ReturnType<typeof blogGetBlogList>>>,
    TError = ErrorType<unknown>,
>(options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof blogGetBlogList>>, TError, TData>>;
}): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
    const queryOptions = getBlogGetBlogListInfiniteQueryOptions(options);

    const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

export const getBlogGetBlogListQueryOptions = <
    TData = Awaited<ReturnType<typeof blogGetBlogList>>,
    TError = ErrorType<unknown>,
>(options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof blogGetBlogList>>, TError, TData>>;
}) => {
    const { query: queryOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getBlogGetBlogListQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof blogGetBlogList>>> = ({ signal }) => blogGetBlogList(signal);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof blogGetBlogList>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData> };
};

export type BlogGetBlogListQueryResult = NonNullable<Awaited<ReturnType<typeof blogGetBlogList>>>;
export type BlogGetBlogListQueryError = ErrorType<unknown>;

export function useBlogGetBlogList<
    TData = Awaited<ReturnType<typeof blogGetBlogList>>,
    TError = ErrorType<unknown>,
>(options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof blogGetBlogList>>, TError, TData>> &
        Pick<DefinedInitialDataOptions<Awaited<ReturnType<typeof blogGetBlogList>>, TError, TData>, 'initialData'>;
}): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useBlogGetBlogList<
    TData = Awaited<ReturnType<typeof blogGetBlogList>>,
    TError = ErrorType<unknown>,
>(options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof blogGetBlogList>>, TError, TData>> &
        Pick<UndefinedInitialDataOptions<Awaited<ReturnType<typeof blogGetBlogList>>, TError, TData>, 'initialData'>;
}): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useBlogGetBlogList<
    TData = Awaited<ReturnType<typeof blogGetBlogList>>,
    TError = ErrorType<unknown>,
>(options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof blogGetBlogList>>, TError, TData>>;
}): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

export function useBlogGetBlogList<
    TData = Awaited<ReturnType<typeof blogGetBlogList>>,
    TError = ErrorType<unknown>,
>(options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof blogGetBlogList>>, TError, TData>>;
}): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
    const queryOptions = getBlogGetBlogListQueryOptions(options);

    const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

    query.queryKey = queryOptions.queryKey;

    return query;
}
