/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Project API
 * OpenAPI spec version: 1.0
 */
export type MarketItemStatus = (typeof MarketItemStatus)[keyof typeof MarketItemStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MarketItemStatus = {
    ACTIVE: 'ACTIVE',
    ERROR: 'ERROR',
    DISABLED: 'DISABLED',
} as const;

export interface MarketItem {
    currency: string;
    id: number;
    price: string;
    status: MarketItemStatus;
}

export interface MarketList {
    items: MarketItem[];
}

export interface CommentItem {
    comment: string;
    date: string;
    id: number;
    like: string;
    name: string;
    postId: number;
}

export interface CommentList {
    items: CommentItem[];
}

export interface BlogItem {
    avatar: string;
    content: string;
    date: string;
    id: number;
    like: string;
    shortDescription: string;
    title: string;
}

export interface BlogListItem {
    avatar: string;
    date: string;
    id: number;
    like: string;
    shortDescription: string;
    title: string;
}

export interface BlogList {
    items: BlogListItem[];
}

export interface HistoryItem {
    date: string;
    id: number;
    pair: string;
    profit: number;
    userId: number;
}

export interface HistoryList {
    items: HistoryItem[];
}

export interface WalletItem {
    BNB: string;
    BTC: string;
    DOGE: string;
    SOL: string;
    USDT: string;
    userId: number;
    XRP: string;
}

export interface User {
    group: number;
    id: number;
    name: string;
    password: string;
    username: string;
}

export interface AuthType {
    access_token: string;
}

export interface AuthDto {
    password: string;
    username: string;
}
