/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Project API
 * OpenAPI spec version: 1.0
 */
export interface AuthType {
    access_token: string;
}

export interface AuthDto {
    password: string;
    username: string;
}
