import { Metadata } from 'next';
import Head from 'next/head';
import { AppLayout } from './app.layout';

export const metadata: Metadata = {
    title: 'Bitfinex',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <Head>
                <link rel="icon" href="/favicon.png" type="image/png" />
            </Head>
            <body>
                <AppLayout>{children}</AppLayout>
            </body>
        </html>
    );
}
