import { Col } from '@/shared/ui/boxes';
import { Typography } from '@mui/material';

export const TermsMain = () => {
    return (
        <Col m={6} gap={4}>
            <Typography color="white" fontWeight={700} fontSize={36}>
                Terms of Service
            </Typography>

            <Typography color="white" fontWeight={700} fontSize={24}>
                Bitfinex Privacy Statement
            </Typography>

            <Typography>Last updated November 13, 2024</Typography>

            <Typography color="white" fontWeight={700}>
                IMPORTANT: By creating or funding an Account or accessing or using any of the Services (each as defined
                below), you acknowledge that you have read, understand, and completely agree to these Terms of Service,
                as updated and amended from time to time. If you do not agree to be bound by these Terms of Service or
                with any subsequent amendments, changes or updates, you may not access or use any of the Services, and
                if you do access or use any of the Services, you will be bound by these Terms of Service, as updated and
                amended from time to time; your only recourse in the case of your unwillingness to be bound by these
                Terms of Service is to stop using all of the Services. These Terms of Service were last updated on
                November 6, 2024.
            </Typography>
            <Typography>
                Only eligible Persons are permitted to access or use the Services. Any Person that is not eligible that
                utilizes the Services or that accesses the Site will be in breach of these Terms of Service and may have
                any Fiat, Digital Tokens, funds, proceeds or other property, confiscated (all as defined below).
            </Typography>
            <Typography>
                These Terms of Service apply to users of Bitfinex.com (all web pages at such address, including the
                mobile application and application programming interfaces, are sometimes referred to as the “Site”). You
                should read these Terms of Service carefully to determine which provisions apply to you. These Terms of
                Service should be read in conjunction with the terms of service applicable to other web pages of the
                Site, which will apply to you in respect of the services identified, which shall be in addition to these
                Terms of Service and shall not be exclusive. For example, use of the Derivatives web pages of the Site
                and the trading of any derivative products are governed by Derivative Terms of Service. By creating or
                funding an Account or accessing or using any of the services, functions, or features offered from time
                to time on the Site (collectively or individually, the “Services”), the user (referred to herein as
                “you” or “your”) agrees to these Terms of Service.
            </Typography>
            <Typography>
                These Terms of Service, together with the incorporated materials, constitute the entire agreement and
                understanding with respect to the access or use of any or all of the Services, and any manner of
                accessing them via the Site, between you and one of the following Bitfinex parties:
            </Typography>
            <Typography>
                Important: Please do not use any deposit addresses created before August 9, 2016 at 19:00:00 UTC to
                deposit any Digital Tokens to or on the Site. Use only addresses generated by and on the Site after
                August 9, 2016 at 19:00:00 UTC. Among other limitations of liability, Bitfinex cannot and shall not be
                responsible or liable for any deposits to any Digital Tokens Wallet(s) or Digital Tokens Address(es)
                created before August 9, 2016 at 19:00:00 UTC.
            </Typography>
            <Typography>
                If any of the criteria set out in paragraph (b)(1) through (b)(2) above apply, then you are a “BFXNA
                Customer.” Otherwise, you are a “BFXWW Customer.” Each of you and BFXWW or BFXNA, as applicable, are a
                “Party” and, collectively, the “Parties”.
            </Typography>
            <Typography>
                The following documents are incorporated into these Terms of Service by reference: the API Terms of
                Service; the Bitfinex Chatbot Terms of Service; the General Rules for Competitions on Bitfinex.com; the
                Bitfinex Market Data Terms of Use; the Risk Disclosure Statement; the Anti-Spam Policy; the Law
                Enforcement Requests Policy; and the Fees Schedule. Also, these Terms of Service should be read in
                conjunction with the Privacy Statement and the Cookies Policy. In particular, please note that all
                transactions of Digital Tokens on or off the Site may be subject to fees levied by Bitfinex as set out
                and updated in the Fees Schedule from time to time, or as otherwise agreed between you and Bitfinex. In
                the event of any inconsistency between these Terms of Service and any other pages, policies, terms,
                conditions, licenses, limitations, or obligations contained within or on the Site, these Terms of
                Service shall prevail.
            </Typography>
            <Typography>
                PLEASE REVIEW THE ARBITRATION PROVISION SET FORTH BELOW CAREFULLY, AS IT REQUIRES ALL BFXNA CUSTOMERS TO
                BRING ANY CLAIMS AND TO RESOLVE DISPUTES ON AN INDIVIDUAL BASIS THROUGH FINAL AND BINDING ARBITRATION.
                BY UTILIZING THE SERVICES, YOU EXPRESSLY ACKNOWLEDGE THAT YOU HAVE READ AND UNDERSTAND ALL OF THESE
                TERMS OF SERVICE AND HAVE TAKEN TIME TO CONSIDER THE CONSEQUENCES OF THIS IMPORTANT DECISION.
            </Typography>
            <Typography>
                The Services are complex and carry a high level of risk and are not appropriate for users who do not
                possess the appropriate level of knowledge and experience to deal in them. Bitfinex is under no
                obligation to assess the suitability of the Services for users and any comment or statement which may be
                made by Bitfinex or any of its Associates as to the suitability of the Services to you should under no
                circumstances be considered as investment or legal advice and should not be received or relied upon as
                such. For further information on the risks of the Services, you can review the Risk Disclosure
                Statement.
            </Typography>
            <Typography>
                These Terms of Service may be amended, changed, or updated by Bitfinex at any time and without prior
                notice to you. You should check back often on the Site to confirm that your copy and understanding of
                these Terms of Service is current and correct. Your non-termination or continued access or use of any
                Services after the effective date of any amendments, changes, or updates constitutes your acceptance of
                these Terms of Service, as modified by such amendments, changes, or updates.
            </Typography>
            <Typography>
                The access or use of the Site and any of the Services is void where such access or use is prohibited by,
                would constitute a violation of, or would be subject to penalties under applicable Laws, and shall not
                be the basis for the assertion or recognition of any interest, right, remedy, power, or privilege.
            </Typography>
            <Typography>
                You hereby agree to release the Associates from liability for any and all such Losses, and you shall
                indemnify and save and hold the Associates harmless from and against all such Losses. To the maximum
                extent permitted by applicable Law, the foregoing limitations of liability, releases and indemnities
                shall apply whether the alleged liability or Losses are based on contract, negligence, tort, unjust
                enrichment, strict liability, violation of law or regulation, or any other basis, even if the Associates
                have been advised of or should have known of the possibility of such Losses and damages, and without
                regard to the success or effectiveness of any other remedies.
            </Typography>
            <Typography>
                No Insurance: You acknowledge that Digital Tokens and Fiat are not subject to the protections or
                insurance provided by any Government. In addition, although any Person may maintain insurance for its
                own benefit in connection with its business, this insurance, if maintained, is solely for the benefit of
                such Person and does not guarantee or insure the other user of the Site in any way.
            </Typography>
            <Typography>
                No Waiver; Available Remedies: Any failure by any Associate to exercise any of its rights, powers, or
                remedies under these Terms of Service, or any delay by any Associate in doing so, does not constitute a
                waiver of any such right, power, or remedy. The single or partial exercise of any right, power, or
                remedy by any Associate does not prevent any of them from exercising any other rights, powers, or
                remedies. The remedies of any Associate are cumulative with and not exclusive of any other remedy
                conferred by the provisions of these Terms of Service, or by law or equity. You agree that the remedies
                to which any Associate is entitled include (i) injunctions to prevent breaches of these Terms of Service
                and to enforce specifically the terms and provisions hereof, and you waive the requirement of any
                posting of a bond in connection with such remedies, (ii) the right to recover the amount of any Losses
                by set off against any amounts that Bitfinex would otherwise be obligated to pay to you, and (iii) the
                right to seize and recover against any of your Digital Tokens, Fiat or other funds or your interests
                therein, that are held by Bitfinex or any of its Associates.
            </Typography>
        </Col>
    );
};
