/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Project Admin API
 * OpenAPI spec version: 1.0
 */
export interface AuthResponse {
    authToken: string;
}

export interface AuthDto {
    login: string;
    password: string;
}

export interface Wallet {
    BNB: string;
    BTC: string;
    DOGE: string;
    SOL: string;
    USDT: string;
    userId: number;
    XRP: string;
}

export interface User {
    id: number;
    name: string;
    password: string;
    username: string;
}

export interface UserList {
    items: User[];
}

export interface UserCreateDto {
    name: string;
    password: string;
    username: string;
}
