/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Project Admin API
 * OpenAPI spec version: 1.0
 */
export interface CommentItem {
    comment: string;
    date: string;
    id: number;
    like: string;
    name: string;
    postId: number;
}

export interface CommentList {
    items: CommentItem[];
}

export interface CreateCommentDto {
    comment: string;
    date: string;
    like: string;
    name: string;
    postId: number;
}

export interface BlogItem {
    avatar: string;
    content: string;
    date: string;
    id: number;
    like: string;
    shortDescription: string;
    title: string;
}

export interface BlogListItem {
    date: string;
    id: number;
    like: string;
    shortDescription: string;
    title: string;
}

export interface BlogList {
    items: BlogListItem[];
}

export interface CreateBlogDto {
    avatar: string;
    content: string;
    date: string;
    like: string;
    shortDescription: string;
    title: string;
}

export interface NewAdminDto {
    login: string;
    password: string;
}

export interface AdminType {
    id: number;
    login: string;
    password: string;
    root: boolean;
}

export interface AdminList {
    items: AdminType[];
}

export interface AuthResponse {
    authToken: string;
}

export interface AuthDto {
    login: string;
    password: string;
}

export interface HistoryDto {
    date: string;
    pair: string;
    profit: string;
    userId: string;
}

export interface HistoryItem {
    date: string;
    id: number;
    pair: string;
    profit: number;
    userId: number;
}

export interface HistoryList {
    items: HistoryItem[];
}

export interface Wallet {
    BNB: string;
    BTC: string;
    DOGE: string;
    SOL: string;
    USDT: string;
    userId: number;
    XRP: string;
}

export interface User {
    group: number;
    id: number;
    name: string;
    password: string;
    username: string;
}

export interface UserList {
    items: User[];
}

export interface UserCreateDto {
    name: string;
    password: string;
    username: string;
}
