/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Project Admin API
 * OpenAPI spec version: 1.0
 */
export interface AuthResponse {
    authToken: string;
}

export interface AuthDto {
    login: string;
    password: string;
}

export interface HistoryItem {
    date: string;
    id: number;
    pair: string;
    profit: number;
    userId: number;
}

export interface HistoryList {
    items: HistoryItem[];
}

export interface HistoryDto {
    date: string;
    pair: string;
    profit: number;
    userId: number;
}

export interface User {
    balance: number;
    id: number;
    password: string;
    profit_1: number;
    profit_24: number;
    profit_7: number;
    username: string;
}

export interface UserList {
    items: User[];
}

export interface UserCreateDto {
    balance: number;
    password: string;
    username: string;
}
